import "../src/loadEnv.js";
import express from "express";
import multer from "multer";
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { generateVideoScriptWithGemini, naiveFallbackScript } from "../src/scriptGenerator.js";

const PORT = 4174;
const root = path.resolve(import.meta.dirname, "..");
const assetsDir = path.join(root, "assets");
const dataDir = path.join(root, "data");
const outDir = path.join(root, "out");
const docsDir = path.join(dataDir, "uploaded-documents");
const scriptPath = path.join(dataDir, "billings-invoices.json");

for (const dir of [assetsDir, docsDir, outDir]) fs.mkdirSync(dir, { recursive: true });

const app = express();
app.use(express.json({ limit: "5mb" }));
app.use("/out", express.static(outDir));

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 500 * 1024 * 1024 } });

function safeName(name: string) {
  return name.replace(/[^a-zA-Z0-9_.-]/g, "_");
}

app.get("/admin", (_req, res) => {
  res.sendFile(path.join(import.meta.dirname, "admin.html"));
});

/**
 * Step 1: the uploaded script is plain narration TEXT — what should be said,
 * not the video's shot structure. Claude (if ANTHROPIC_API_KEY is set) turns
 * that text, plus the supporting documents and directions, into the ordered
 * scene JSON (docs/video-pipeline-plan.md §3, step 1). That generated JSON —
 * not the raw upload — is what goes to the reviewer next. Falls back to a
 * naive paragraph split with no API key, clearly labeled as such.
 */
app.post(
  "/admin/prepare",
  upload.fields([
    { name: "scriptFile", maxCount: 1 },
    { name: "demoVideo", maxCount: 1 },
    { name: "documents", maxCount: 10 },
  ]),
  async (req, res) => {
    try {
      const files = req.files as Record<string, Express.Multer.File[]> | undefined;
      const directions = (req.body?.directions ?? "").toString();
      const warnings: string[] = [];

      if (!files?.scriptFile?.[0]) {
        return res.status(400).json({ ok: false, error: "Upload a script file (plain text — what should be said)." });
      }
      const scriptText = files.scriptFile[0].buffer.toString("utf-8");

      const base: any = fs.existsSync(scriptPath)
        ? JSON.parse(fs.readFileSync(scriptPath, "utf-8"))
        : { slug: "billings-invoices", title: "Keeping track of client billings and invoices", category: "administrative" };

      const documents: { name: string; text: string }[] = [];
      if (files?.documents?.length) {
        for (const doc of files.documents) {
          const destName = `${Date.now()}_${safeName(doc.originalname)}`;
          fs.writeFileSync(path.join(docsDir, destName), doc.buffer);
          documents.push({ name: doc.originalname, text: doc.buffer.toString("utf-8") });
        }
        warnings.push(`${files.documents.length} document(s) saved to data/uploaded-documents/ and passed to script generation as context.`);
      }

      if (directions.trim()) {
        fs.writeFileSync(path.join(dataDir, "last-directions.txt"), directions, "utf-8");
      }

      let videoScript;
      if (process.env.GEMINI_API_KEY) {
        videoScript = await generateVideoScriptWithGemini({
          slug: base.slug,
          title: base.title,
          scriptText,
          documents,
          directions,
        });
        warnings.push("Scene plan generated by Gemini from your script, documents and directions — review it carefully before rendering, same as any AI-drafted output on this site.");
      } else {
        videoScript = naiveFallbackScript(scriptText, base.slug);
        warnings.push("GEMINI_API_KEY not set — used a naive paragraph split instead of an LLM-planned scene structure. Set the key in .env for real script generation; treat this output as a rough draft only.");
      }

      if (files?.demoVideo?.[0]) {
        const demo = files.demoVideo[0];
        const destName = `UPLOADED_${Date.now()}_${safeName(demo.originalname)}`;
        fs.writeFileSync(path.join(assetsDir, destName), demo.buffer);
        const screenScene = videoScript.find((s: any) => s.type === "screen_recording");
        if (screenScene) {
          (screenScene as any).assetRef = destName;
        } else {
          warnings.push("No screen_recording scene was generated — uploaded demo video was saved but not attached.");
        }
      }

      const script = { ...base, videoScript, videoAsset: { url: null, captionsUrl: null, generatedAt: null, sourceCopyHash: null } };
      res.json({ ok: true, script, warnings });
    } catch (err: any) {
      res.status(400).json({ ok: false, error: err.message });
    }
  }
);

/**
 * Step 2: the (possibly hand-edited) script from the review step is written
 * to disk and the real pipeline runs against it — same code path as the CLI
 * (`npm run generate-narration && npm run render`), just triggered from the
 * browser instead of the terminal.
 */
app.post("/admin/render", (req, res) => {
  let log = "";
  try {
    const script = JSON.parse(req.body.scriptText);
    fs.writeFileSync(scriptPath, JSON.stringify(script, null, 2), "utf-8");

    const run = (cmd: string) => {
      log += `\n$ ${cmd}\n`;
      log += execSync(cmd, { cwd: root, encoding: "utf-8" });
    };

    run("npx tsx src/makePlaceholderAssets.ts");
    run("npx tsx src/generateNarrationVideo.ts");
    run("npx remotion render remotion/index.ts ProblemVideo out/billings-invoices.mp4");

    res.json({ ok: true, videoUrl: `/out/billings-invoices.mp4?t=${Date.now()}`, log });
  } catch (err: any) {
    res.status(500).json({
      ok: false,
      error: err.message,
      log: log + (err.stdout?.toString() ?? "") + (err.stderr?.toString() ?? ""),
    });
  }
});

app.listen(PORT, () => {
  console.log(`Admin pipeline UI: http://localhost:${PORT}/admin`);
});
